//app
export const AUTORIZACION_SPOTIFY = 'AUTORIZACION_SPOTIFY';
export const OBTENER_PLAYLIST_SPOTIFY = 'OBTENER_PLAYLIST_SPOTIFY';
export const OBTENER_PLAYLIST_SPOTIFY_EXITO = 'OBTENER_PLAYLIST_SPOTIFY_EXITO';
export const OBTENER_PLAYLIST_SPOTIFY_ERROR = 'OBTENER_PLAYLIST_SPOTIFY_ERROR';
export const UPDATE_TOKEN_SPOTIFY = 'UPDATE_TOKEN_SPOTIFY';
export const UPDATE_STATE_TOKEN = 'UPDATE_STATE_TOKEN';
export const SELECCIONAR_PLAYLIST_SPOTIFY = 'SELECCIONAR_PLAYLIST_SPOTIFY';
export const GUARDAR_PLAYLIST = 'GUARDAR_PLAYLIST';
export const GUARDAR_DISPOSITIVO = 'GUARDAR_DISPOSITIVO';
export const SAVE_ALARM = 'SAVE_ALARM';
